import React from "react";
import { C } from "./theme";

// ── Illustrations ─────────────────────────────────────────────────────────────
export const Illus = {
  umbrella: React.createElement("svg", {viewBox:"0 0 120 80",fill:"none"},
    React.createElement("ellipse",{cx:"60",cy:"32",rx:"38",ry:"20",fill:C.s1,opacity:".15"}),
    React.createElement("path",{d:"M22 32 Q60 4 98 32",stroke:C.s1,strokeWidth:"2.5",fill:C.s1,fillOpacity:".2"}),
    React.createElement("line",{x1:"60",y1:"32",x2:"60",y2:"70",stroke:C.s1,strokeWidth:"2.5",strokeLinecap:"round"}),
    React.createElement("path",{d:"M60 70 Q66 76 62 78",stroke:C.s1,strokeWidth:"2.5",strokeLinecap:"round",fill:"none"}),
  ),
  silence: React.createElement("svg", {viewBox:"0 0 120 80",fill:"none"},
    React.createElement("circle",{cx:"60",cy:"40",r:"28",stroke:C.s1,strokeWidth:"1.5",opacity:".2",fill:C.s1,fillOpacity:".05"}),
    React.createElement("circle",{cx:"60",cy:"40",r:"18",stroke:C.s1,strokeWidth:"1.5",opacity:".3",fill:C.s1,fillOpacity:".07"}),
    React.createElement("circle",{cx:"60",cy:"40",r:"8",fill:C.s1,opacity:".2"}),
  ),
  rat: React.createElement("svg", {viewBox:"0 0 120 80",fill:"none"},
    React.createElement("rect",{x:"8",y:"28",width:"28",height:"22",rx:"6",fill:C.s1,fillOpacity:".12",stroke:C.s1,strokeWidth:"1.2",opacity:".4"}),
    React.createElement("rect",{x:"46",y:"28",width:"28",height:"22",rx:"6",fill:C.s1,fillOpacity:".12",stroke:C.s1,strokeWidth:"1.2",opacity:".4"}),
    React.createElement("rect",{x:"84",y:"28",width:"28",height:"22",rx:"6",fill:C.s1,fillOpacity:".12",stroke:C.s1,strokeWidth:"1.2",opacity:".4"}),
  ),
  risk: React.createElement("svg", {viewBox:"0 0 120 80",fill:"none"},
    React.createElement("path",{d:"M60 10 L90 65 L30 65 Z",fill:C.s2,fillOpacity:".1",stroke:C.s2,strokeWidth:"1.5",opacity:".4"}),
    React.createElement("circle",{cx:"60",cy:"45",r:"4",fill:C.s2,opacity:".4"}),
  ),
  vision: React.createElement("svg", {viewBox:"0 0 120 80",fill:"none"},
    React.createElement("path",{d:"M20 50 Q60 10 100 50",stroke:C.s3,strokeWidth:"2",fill:"none",opacity:".3"}),
    React.createElement("circle",{cx:"60",cy:"40",r:"9",fill:C.s3,fillOpacity:".2",stroke:C.s3,strokeWidth:"1.5",opacity:".5"}),
    React.createElement("circle",{cx:"60",cy:"40",r:"4",fill:C.s3,opacity:".4"}),
  ),
  behavior: React.createElement("svg", {viewBox:"0 0 120 80",fill:"none"},
    React.createElement("rect",{x:"15",y:"20",width:"25",height:"40",rx:"4",fill:C.s4,fillOpacity:".1",stroke:C.s4,strokeWidth:"1.2",opacity:".35"}),
    React.createElement("rect",{x:"47",y:"30",width:"25",height:"30",rx:"4",fill:C.s4,fillOpacity:".15",stroke:C.s4,strokeWidth:"1.2",opacity:".45"}),
    React.createElement("rect",{x:"79",y:"15",width:"25",height:"45",rx:"4",fill:C.s4,fillOpacity:".2",stroke:C.s4,strokeWidth:"1.2",opacity:".55"}),
  ),
  innovation: React.createElement("svg", {viewBox:"0 0 120 80",fill:"none"},
    React.createElement("circle",{cx:"60",cy:"38",r:"22",fill:C.s5,fillOpacity:".08",stroke:C.s5,strokeWidth:"1.5",opacity:".3"}),
    React.createElement("path",{d:"M60 16 L64 30 L78 30 L67 39 L71 53 L60 44 L49 53 L53 39 L42 30 L56 30Z",fill:C.s5,fillOpacity:".2",stroke:C.s5,strokeWidth:"1",opacity:".4"}),
  ),
};

// ── Questions ─────────────────────────────────────────────────────────────────
export const Qs = [
  // ── SECTION 1: Cognitive Creativity ──────────────────────────
  {id:"q1",  s:1, type:"open",    illus:Illus.umbrella,   text:"List every possible use for a broken umbrella.",
   hint:"Physical · metaphorical · artistic · absurd · scientific — push far past the obvious.", ph:"One idea per line..."},
  {id:"q2",  s:1, type:"open",    illus:Illus.silence,    text:"In how many ways could complete SILENCE be a valuable tool or resource?",
   hint:"Therapy · technology · business · art · military · nature · education...", ph:"One idea per line..."},
  {id:"q3",  s:1, type:"rat",     illus:Illus.rat,        text:"Find ONE word that connects all three:",
   words:["PINE","CRAB","SAUCE"], options:["APPLE","TREE","FRUIT","JUICE"], answer:"APPLE"},
  {id:"q4",  s:1, type:"rat",     illus:Illus.rat,        text:"Find ONE word that connects all three:",
   words:["FALLING","ACTOR","DUST"], options:["FILM","SKY","STAR","STAGE"], answer:"STAR"},
  {id:"q5",  s:1, type:"rat",     illus:Illus.rat,        text:"Find ONE word that connects all three:",
   words:["LIGHT","BIRTHDAY","STICK"], options:["WAX","PARTY","FIRE","CANDLE"], answer:"CANDLE"},

  // ── SECTION 2: Inner Landscape ───────────────────────────────
  {id:"q6",  s:2, type:"likert",  illus:Illus.risk, text:"I feel energized — not anxious — when starting a project with no clear direction."},
  {id:"q7",  s:2, type:"likert",  illus:Illus.risk, text:"Failure feels like useful data to me, not a personal setback."},
  {id:"q8",  s:2, type:"likert",  illus:Illus.risk, text:"I regularly explore topics completely unrelated to my work, purely out of curiosity."},
  {id:"q9",  s:2, type:"likert",  illus:Illus.risk, text:"I actively seek out people who think very differently from me."},
  {id:"q10", s:2, type:"likert",  illus:Illus.risk, reversed:true,
   text:"I find it unsettling when a situation has no clear right answer or obvious path forward."},

  // ── SECTION 3: Vision & Drive ─────────────────────────────────
  {id:"q11", s:3, type:"likert",  illus:Illus.vision, text:"I can vividly imagine products, systems, or worlds that don't yet exist."},
  {id:"q12", s:3, type:"likert",  illus:Illus.vision, text:"I continue working on ideas even when no one around me believes in them yet."},
  {id:"q13", s:3, type:"likert",  illus:Illus.vision, text:"I feel compelled to build or create things even without any external reward."},
  {id:"q14", s:3, type:"likert",  illus:Illus.vision, text:"I often stop mid-task to question whether I'm solving the RIGHT problem."},
  {id:"q15", s:3, type:"likert",  illus:Illus.vision, reversed:true,
   text:"I tend to lose momentum on creative ideas once the initial excitement fades."},

  // ── SECTION 4: Creative Behavior ─────────────────────────────
  {id:"q16", s:4, type:"mcq",     illus:Illus.behavior,
   text:"When you encounter a frustrating, broken process, you typically:",
   options:["Accept it and adapt around it","Work around it quietly on your own","Propose a better way to whoever's responsible","Redesign or fix it yourself without waiting"],
   scores:[1,2,3,4]},
  {id:"q17", s:4, type:"mcq",     illus:Illus.behavior,
   text:"How often do you connect ideas from completely unrelated fields to solve your problems?",
   options:["Almost never","Occasionally when stuck","Regularly — one of my first approaches","It's my default way of thinking"],
   scores:[1,2,3,4]},
  {id:"q18", s:4, type:"mcq",     illus:Illus.behavior,
   text:"In the last year, have you created something — a product, system, or solution — that didn't exist before?",
   options:["Not really","Started something but didn't finish","Yes, once or twice","Yes, multiple times"],
   scores:[1,2,3,4]},
  {id:"q19", s:4, type:"mcq",     illus:Illus.behavior,
   text:"Your relationship with constraints — deadlines, budgets, rules:",
   options:["They frustrate and block my thinking","I just work with what I have","They often make me think more creatively","I actively create constraints to spark better ideas"],
   scores:[1,2,3,4]},
  {id:"q20", s:4, type:"mcq",     illus:Illus.behavior,
   text:"When someone dismisses your creative idea, you typically:",
   options:["Let it go — they may be right","Feel frustrated but move on","Seek their reasoning to understand why","Find another way to demonstrate its merit"],
   scores:[1,2,3,4]},

  // ── SECTION 5: Innovation Thinking ───────────────────────────
  {id:"q21", s:5, type:"scenario", scene:"🏢", sceneLabel:"STARTUP CRISIS", illus:Illus.innovation,
   text:"Your startup's main product just became obsolete overnight.",
   options:["Deeply analyze what makes the competitor's product superior","Immediately negotiate a partnership or acquisition with them","Find a different problem your existing technology could now solve","Pivot to a new market entirely using your team's core skills"],
   scores:[2,2,4,3]},
  {id:"q22", s:5, type:"scenario", scene:"🌉", sceneLabel:"URBAN PROBLEM", illus:Illus.innovation,
   text:"A public bridge keeps getting vandalized despite all traditional interventions.",
   options:["Better surveillance cameras and increased fines","Apply permanent anti-graffiti coating everywhere","Commission local artists to transform it into a mural destination","Demolish and redesign the bridge entirely"],
   scores:[1,2,4,1]},
  {id:"q23", s:5, type:"scenario", scene:"🏫", sceneLabel:"EDUCATION", illus:Illus.innovation,
   text:"You must teach creativity to 10-year-olds. Your most effective approach:",
   options:["Teach classic techniques: brainstorming, mind maps, SCAMPER","Show curated examples of great creative work throughout history","Give them impossible problems with no right answers — then step back","Master techniques, then explicitly teach them to break every rule"],
   scores:[2,2,3,4]},
  {id:"q24", s:5, type:"scenario", scene:"🏙️", sceneLabel:"CITY CHALLENGE", illus:Illus.innovation,
   text:"Your city is losing talented young people to other cities. Most innovative retention strategy:",
   options:["Lower taxes, increase salaries, improve standard amenities","Build better transport, housing, and green spaces","Create a city-wide experimental zone where regulations are suspended","Launch a civic co-ownership model where residents hold real equity"],
   scores:[1,2,3,4]},
  {id:"q25", s:5, type:"scenario", scene:"🧠", sceneLabel:"TECH & HUMANITY", illus:Illus.innovation,
   text:"You've built tech that lets people fully experience another person's memories. You launch it first as:",
   options:["A clinical therapy tool for trauma healing","A courtroom evidence platform","A revolutionary entertainment and art medium beyond VR","An education platform where students literally live history"],
   scores:[3,2,4,4]},
] as const;

export type QuestionId = typeof Qs[number]["id"];
